<a href="https://colab.research.google.com/github/cenebech/DL_PytorchTurorial/blob/main/DeepLearningWithPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np


In [1]:

my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.4368235 , 0.37366389, 0.87653857, 0.46280255],
       [0.01731792, 0.3353504 , 0.35416992, 0.85269512],
       [0.53616391, 0.04027144, 0.17762855, 0.56894523]])

In [8]:

tensor_2d = torch.zeros(2,3,4)
tensor_2d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:

## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4368, 0.3737, 0.8765, 0.4628],
        [0.0173, 0.3354, 0.3542, 0.8527],
        [0.5362, 0.0403, 0.1776, 0.5689]], dtype=torch.float64)