<a href="https://colab.research.google.com/github/cenebech/DL_PytorchTurorial/blob/main/TensorTutorialPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np


In [ ]:

my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.4368235 , 0.37366389, 0.87653857, 0.46280255],
       [0.01731792, 0.3353504 , 0.35416992, 0.85269512],
       [0.53616391, 0.04027144, 0.17762855, 0.56894523]])

In [ ]:

tensor_2d = torch.zeros(2,3,4)
tensor_2d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:

## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4368, 0.3737, 0.8765, 0.4628],
        [0.0173, 0.3354, 0.3542, 0.8527],
        [0.5362, 0.0403, 0.1776, 0.5689]], dtype=torch.float64)

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:

# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

RuntimeError: only one dimension can be inferred

In [ ]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [ ]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:

# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:

# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:

# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [ ]:

# Mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:

# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [ ]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
#tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
tensor_a

tensor([ 6,  8, 10, 12])